services:
    db:
        image: postgres
        ports:
            - 5432:5432

        env_file:
            - ".env"

        volumes:
            - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data:
